repos:
  - repo: https://github.com/psf/black
    rev: 21.8b00
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: tox
        name: tox-check
        entry: python -m tox -p all
        language: system
        pass_filenames: false
        always_run: true
