repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest --cov=pyproject_toml
        language: system
        pass_filenames: false
        always_run: true
